apiVersion: apps/v1
kind: Deployment
metadata:
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: testapp
      tier: testapp
  spec:
    containers:
    - name: testapp
      image: congtruqn/testapp:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: testapp

---
apiVersion: v1
kind: Service
metadata:
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: testapp
  tier: testapp
type: LoadBalancer